"""change_primary_ke

Revision ID: 5a145112da4b
Revises: 82c4e23d187b
Create Date: 2025-06-14 12:37:18.328399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a145112da4b'
down_revision: Union[str, None] = '82c4e23d187b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('time_to_hatch', sa.DateTime(), nullable=True))
    op.add_column('pet', sa.Column('time_to_unhappy', sa.DateTime(), nullable=True))
    op.add_column('pet', sa.Column('time_to_hungry', sa.DateTime(), nullable=True))
    op.add_column('pet', sa.Column('time_to_walk', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'time_to_walk')
    op.drop_column('pet', 'time_to_hungry')
    op.drop_column('pet', 'time_to_unhappy')
    op.drop_column('pet', 'time_to_hatch')
    # ### end Alembic commands ###
