"""initial

Revision ID: 69e45c8d9f5b
Revises: 8a5ed931be09
Create Date: 2025-06-10 08:13:47.000950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e45c8d9f5b'
down_revision: Union[str, None] = '8a5ed931be09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
