"""initial

Revision ID: 8a5ed931be09
Revises: fa2607d7e812
Create Date: 2025-06-09 20:37:58.354629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5ed931be09'
down_revision: Union[str, None] = 'fa2607d7e812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.Column('owner1', sa.BigInteger(), nullable=False),
    sa.Column('owner2', sa.BigInteger(), nullable=False),
    sa.Column('time_to_crack', sa.DateTime(), nullable=False),
    sa.Column('essense', sa.String(), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    # ### end Alembic commands ###
