"""Initial migration

Revision ID: c71bd06a74b7
Revises: c7ea0262369c
Create Date: 2025-10-27 17:33:00.004642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71bd06a74b7'
down_revision: Union[str, None] = 'c7ea0262369c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('next_run_time', sa.DateTime(), nullable=False),
    sa.Column('job_state', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###
